### ISSUE TITLE
作者大大能不能更新下完整点的代码 求求了

### ISSUE THREAD

**Issue by panzuwang** [JerryX1110/Robust-Video-Object-Segmentation#1]

**Comment by JerryX1110** [comment]
您好，感谢您的关注!

我们完整的代码已经开源了，在这个子文件夹中： https://github.com/JerryX1110/Robust-Video-Object-Segmentation/tree/main/AOC-Net/complete_project

**Comment by panzuwang** [comment]
> 

这是一个非常棒的工作，谢谢您的回复以及抽空公布完整代码，这对我来说十分有帮助。

**Comment by JerryX1110** [comment]
谢谢！为了帮助您对code实现细节的了解，我在code 里面加了一些注释，然后您在看repo的时候可以注意以下几个文件(夹)：

本文网络模型完整code在这个文件夹下：https://github.com/JerryX1110/Robust-Video-Object-Segmentation/tree/main/AOC-Net/complete_project
多聚类 Object proxy construction以及proxy和query embedding matching的实现请参考：https://github.com/JerryX1110/Robust-Video-Object-Segmentation/blob/main/AOC-Net/complete_project/AOCNet/networks/aoc/aocnet.py 和 https://github.com/JerryX1110/Robust-Video-Object-Segmentation/blob/main/AOC-Net/adaptive_embedding_for_matching.py
Object mask calibration的实现请参考：https://github.com/JerryX1110/Robust-Video-Object-Segmentation/blob/main/AOC-Net/complete_project/AOCNet/networks/aoc/conditioning_layer.py 和https://github.com/JerryX1110/Robust-Video-Object-Segmentation/blob/main/AOC-Net/complete_project/AOCNet/networks/aoc/decoding_module.py
Robust VOS benchmarking的实现在这个文件夹下： https://github.com/JerryX1110/Robust-Video-Object-Segmentation/tree/main/Robust-VOS-Benchmark
 
祝好~
