### ISSUE TITLE
trained model weights

### ISSUE THREAD

**Issue by Student204161** [JerryX1110/Robust-Video-Object-Segmentation#4]
Thanks for your work,

I wanted to ask whether there are any plans for sharing the trained weights, so I would be able to test specifc use cases without having to spend days training.

**Comment by JerryX1110** [comment]
Hi! Thanks for your interest in our work. However, as the checkpoint of the trained model is the property of my previous company (Microsoft) to take an internship, I could not have access to that right know. So maybe you have to train the model on your own.&nbsp;
If you have any questions or meet with any problems during the training, feel free to let me know and I am glad to help you. By the way, I am happy to know there is someone cool to go on push the frontier of robust vos forward!&nbsp; : )&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 21, 2023 01:45 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JerryX1110/Robust-Video-Object-Segmentation] trained model weights(Issue #4)




 
Thanks for your work,
 
I wanted to ask whether there are any plans for sharing the trained weights, so I would be able to test specifc use cases without having to spend days training.

**Comment by Student204161** [comment]
That is understandable, thanks for your quick answer.
